### ISSUE TITLE
Rhdf5lib fails silently if zlib compression not supported (required for 1 use-case)

### ISSUE THREAD

**Issue by warrenmcg** [Huber-group-EMBL/Rhdf5lib#15]
Hi @grimbough,

I just wanted to bring your attention to an issue thread on sleuth's repository (pachterlab/sleuth#120). The root cause of this seems to originate with an edge case involving Rhdf5lib.

Users were getting a cryptic error message:
```
Error in H5Fopen(file, "H5F_ACC_RDONLY") : 
HDF5. File accessability. Unable to open file.
```

Because of some excellent bug-hunting and troubleshooting by @johanneskoester, we found the problem. Here is [his explanation](https://github.com/pachterlab/sleuth/issues/120#issuecomment-458044547):
> one issue that certainly occurs also when installing directly is that, if zlib headers are not found, rhdf5lib will silently compile without zlib compression support. Then, upon using it, you get these not very descriptive error messages posted here whenever reading a dataset with zlib compressed tables.

Sleuth reads kallisto-created HDF5 files, and kallisto uses gz compression to keep the files small, thus zlib compression is required. @johanneskoester did some excellent work creating a bioconda recipe (bioconda/bioconda-recipes#12780) to include a test case and make sure zlib compression is available.

I just wanted to bring this to your attention so that a similar check can be included in the bioconductor release of these packages.

**Comment by grimbough** [comment]
Thanks for the report. I assumed R would require zlib, and so it would be available, but my knowledge of bioconda is pretty small.  I'll checking with that issue if I need more details.

I've also created a **rhdf5** branch (https://github.com/grimbough/rhdf5/tree/H5Z) to try and provide a more helpful error message if it happens in the future.  It seems a shame HDF5 doesn't report the problem more specificially itself, but there appears to be functionality for listing and checking filters.

**Comment by warrenmcg** [comment]
Great, thanks for checking in and for your work in improving *rhdf5*!

I'm pinging @johanneskoester, just so he's kept in the loop about further rhdf5 development. He may have some insight about why zlib might not be available with bioconda.

I'm not sure if the only users who have reported an error are installing R through bioconda, or if any are doing the native install and installing rhdf5 through bioconductor. I personally have never reproduced the error from my end (using a native-R/bioconductor build).

In any case, I think having a helpful error message will make it easier for sleuth to provide an informative error message for our users.

**Comment by johanneskoester** [comment]
With bioconda, we ensure that packages are built in an environment that has nothing available. This way, software usually complains when a dependency is missing and we can add it to the package (as a dependency in the metadata). If now, like here, the software does not complain, such things can happen. That's why I appreciate a lot that this behavior is now being changed.

This is e.g. the code of the rhdf5lib recipe:
```
{% set version = "1.4.2" %}
{% set name = "Rhdf5lib" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 05dbaf6e2c8cebfe41e4e5a98f8a75ed
  patches:
    - configure.patch
build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - zlib
  run:
    - r-base
    - zlib
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Provides C and C++ hdf5 libraries.'
```

As you can see, all dependencies are listed explicitly, which allows conda to take care of installing them along with the rhdf5lib package.
